openapi: 3.0.0
info:
  title: Talenvo Healthcare App API
  description: Location-based healthcare search application that finds healthcare providers based on user location and preferences
  version: 1.0.0
  contact:
    name: Talenvo Healthcare Support
    email: support@talenvo.com

servers:
  - url: 'localhost:3000/api/v1'
    variables:
      URL:com
        default: http://localhost:3000/api/v1
        description: Base URL for the Talenvo Healthcare App API

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'localhost:3000/api/v1/auth/login'
          scopes:
            read: Read access to user profile and healthcare search
            write: Modify user profile and perform actions

  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
    
    HealthcareProvider:
      type: object
      properties:
        name:
          type: string
        location:
          type: array
          items:
            type: number
        distance:
          type: number
        specialty:
          type: string

paths:
  /auth/register:
    post:
      summary: Register a new user account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Successfully registered user

  /auth/verify-email/{token}:
    get:
      summary: Verify user email
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Email successfully verified

  /auth/login:
    post:
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /auth/forgot-password:
    post:
      summary: Initiate password reset
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Password reset instructions sent

  /auth/reset-password/{token}:
    post:
      summary: Reset user password
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Password successfully reset

  /user/me:
    get:
      summary: Get current user profile
      security:
        - OAuth2: [read]
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /search:
    get:
      summary: General healthcare search
      parameters:
        - in: query
          name: AddressSearch[address]
          schema:
            type: string
      security:
        - OAuth2: [read]
      responses:
        '200':
          description: Successful search
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthcareProvider'

  /search/filter:
    get:
      summary: Filter healthcare providers
      parameters:
        - in: query
          name: userLocation[]
          schema:
            type: array
            items:
              type: number
          description: Latitude and Longitude of user location
        - in: query
          name: maxDistance
          schema:
            type: number
          description: Maximum distance in kilometers
        - in: query
          name: keyword
          schema:
            type: string
          description: Healthcare provider specialty or type
      security:
        - OAuth2: [read]
      responses:
        '200':
          description: Filtered healthcare providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthcareProvider'